version: "3.7"

services:
  app:
    build:
      context: .
    image: movie-api
    container_name: movie-api-app
    environment:
      DB_HOST: db
      DB_DATABASE: movie_api_development
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - $PWD:/app
    ports:
      - 80:3000
    networks:
      - internal-net
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: movie-api-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie_api_development
    volumes:
      - $PWD/docker/volumes/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
